### ISSUE TITLE
Recrawling failing for 'Catchy Coleslaw'

### ISSUE THREAD

**Issue by jayaddison** [openculinary/api#43]
**Describe the bug**
During recrawling of [this Catchy Coleslaw](https://www.allrecipes.com/recipe/231963/catchy-coleslaw/) recipe, an error is occuring that leads to a failure to reindex the recipe.

**To Reproduce**
1. Begin tailing the api-worker logs: `kubectl logs deployments/api-worker-deployment -f`
1. Recrawl [Catchy Coleslaw](https://www.allrecipes.com/recipe/231963/catchy-coleslaw/): `pipenv run python recipes.py --where "id = '3ee1MzPJReNVe7Gtv5FaQgY7ky9ctH'" --recrawl`
1. Observe error message:

```
[2020-04-20 10:53:57,493: ERROR/ForkPoolWorker-2] Task reciperadar.workers.recipes.crawl_recipe[e4f8ffd0-5b66-4bd9-93b3-5c38f82726a7] raised unexpected: AttributeError("'NoneType' object has no attribute 'url'")
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/reciperadar/workers/recipes.py", line 82, in crawl_recipe
    recipe_data['src'] = earliest_crawl.url
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by jayaddison** [comment]
https://github.com/openculinary/api/pull/32/commits/b26effdaab9bd8f99cd58627264c77f3362cf2b0 appears to have introduced this bug.
